[[Glib]]
arch = "aarch64"
git-tree-sha1 = "7f50ad342a224a47f88c69f2edbcb0359b528761"
os = "macos"

    [[Glib.download]]
    sha256 = "b5d5bb731d06aa8ac735cbef9d8398076f2797cbf58cc1e435e9e94d74bafe17"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.aarch64-apple-darwin.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "a7d0f5b0ad73a45a5afdfbae95296de28860f4de"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "daefd1410b09cef90004df95016cd58de32e275c2275a393bf2ebe3f7a2204c4"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.aarch64-linux-gnu.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "8b57759d90d447b8823d45d03ed81699f155212e"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "f24072f3011de97b19e4d3afa1439dfbc2a8de6318280c7236ba9778243352a6"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.aarch64-linux-musl.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "1e8a9c5899afd3607e0914e739298afc996cb6bd"
os = "freebsd"

    [[Glib.download]]
    sha256 = "39347364011dae2119ff7293491de868f4d40e9265f835408b1afe6a25cf58d9"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.aarch64-unknown-freebsd.tar.gz"
[[Glib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "993dec00c0cf4c32a6b250cf4928e4ea0ccb5a3d"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "0bfba3b47a00ce2fa6b73b04fc43dbac5a935db21547e3cfd6f2284b9fac0f19"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.armv6l-linux-gnueabihf.tar.gz"
[[Glib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f963376df4b92644ce42749f7b71b9078db492f9"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "0cf8cadb6a2a0bce97789c3980dfe0937734cb35101472952d96a15b4bcc439f"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.armv6l-linux-musleabihf.tar.gz"
[[Glib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "72a17894e083cace143bbb29aa789df067d05364"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "dccb59d650baeaa149c05faf4805b08bc543785d5af072cc05094d73d1f264fc"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.armv7l-linux-gnueabihf.tar.gz"
[[Glib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "463c3232ac56b007aa01a24b007cdfd3dd8dbfa4"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "da4924f57ae58a9309363d717b0d1cef976f79d4613f148bd55e19acbe383feb"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.armv7l-linux-musleabihf.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "4e480cd4b2468a117fc8a403922fef9c78e819d0"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "6a79371b4a65ffaf06d74856fb34266a073dea03bf7d3027eed62d109b9bb72c"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.i686-linux-gnu.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "f580feaa4e4886ba7c530424a96b2177f2b846a9"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "22761b6c9d42845e59636f896f5e41881c9bfda34ca2109a40d5996dd2f9f2fe"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.i686-linux-musl.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "4f737a138c812f67fe7e0fd154b118e9863e65d9"
os = "windows"

    [[Glib.download]]
    sha256 = "46f005c1fa2ad393f6502adf51cc29f48680626ce9c67fd8913b97a8c2fe7d84"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.i686-w64-mingw32.tar.gz"
[[Glib]]
arch = "powerpc64le"
git-tree-sha1 = "b8dcb6959dc590731d238686d3377d91ddbda6c8"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "c0eb766995a7f3fe77e6f2b6c7ce174ae84d3a44f19a1f4625f9ff2c7fbb9613"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.powerpc64le-linux-gnu.tar.gz"
[[Glib]]
arch = "riscv64"
git-tree-sha1 = "d9f684bf856a87fb90b331aa629b28735169e073"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "9e36d5d19d3d5220ec9c89869bf751a646fe97b0051df476fe33fed8e21e87bc"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.riscv64-linux-gnu.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "60535cdf4d3dffc549ae87b29ae604442924cf83"
os = "macos"

    [[Glib.download]]
    sha256 = "2f596f9e93ff638f41a6c1c573d4ce1ba9545dad60e9766b439fdb1f3f02b6bd"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.x86_64-apple-darwin.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "2710f18abd87950eedcef37211b22fb517ee1043"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "cd69aef4e2d9bede684db1c9319ad9f7026894e05ba292774f3f168703d4b5b0"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.x86_64-linux-gnu.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "a3429939faae0b30e3efcea6d59b79f5cce8f608"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "4acd09d51b49e8e886c3e6cb00ba8dc975a405a52adcf8ba6f2265a5f0e94b5a"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.x86_64-linux-musl.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "38108b10e1818c49fd5b9b1b4e2b5def3b7ce437"
os = "freebsd"

    [[Glib.download]]
    sha256 = "8809399416960b4b4f5582e76e8c2c72166e0358d2376f4d88be433c0557957e"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.x86_64-unknown-freebsd.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "c3147644202f8802c6131410ffd73f7e41db31f8"
os = "windows"

    [[Glib.download]]
    sha256 = "541a4317244844d4c4409c0104723954ea1920c9ab89376bd1f4f5b2c67c1ff7"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.x86_64-w64-mingw32.tar.gz"
