[[Glib]]
arch = "aarch64"
git-tree-sha1 = "b1626518aedd33b572f6526773849b918a41154a"
os = "macos"

    [[Glib.download]]
    sha256 = "e86217c26fd275bac30ef66ecf5dffe2260a10cdc2afb37d30b9ff5e0184ce62"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.aarch64-apple-darwin.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "b8f397bc1f3d89ff8a63e0e8cc4ade8715596069"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "eb244663e163f44a01ad296973dc57eee94653e7765f14d651966171294f2b87"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.aarch64-linux-gnu.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "b1e144b0189ae20693d93f05489e06998654dabf"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "79c8690caa27e5c77e8bde45541166cc06d94d1ed761671121a474430149c855"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.aarch64-linux-musl.tar.gz"
[[Glib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "623516dbebd912fa8a4466d2b7557ddb571d4f71"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "d3ad1efb0c85270cecc0ee20cd912f1e55ded118a0035e153d66c37b11f93f7d"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.armv6l-linux-gnueabihf.tar.gz"
[[Glib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b6fd8b31a56d2f45385be2e17b0b1945ec945fd5"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "8347bf3036de24da6364f2005a5a6e14f91d5d0994f4b2fe17d5d9d1995ec48f"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.armv6l-linux-musleabihf.tar.gz"
[[Glib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5b02242773a0503ebdc8e3b520a3dc4e64c75ab2"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "3504a11b6e5e603c4b6c6fa2158e4bcbaaa36005c421f355077b33a173e1cf13"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.armv7l-linux-gnueabihf.tar.gz"
[[Glib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1f3cc5bfc4e15271d8aea25fe926908585c8cedc"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "5919f9f202737bb9d651be27972b206d71570aa0a54fd1472cb418deeddbd010"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.armv7l-linux-musleabihf.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "6f48126ad6568295d1a43639c952399e5c6326c0"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "f7079bdd24161f6909b0a358a97497e659d9ddf5a537601a18ac078225fbcc11"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.i686-linux-gnu.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "0128ec8d07c6a248892c66eda935ab9a65fa667b"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "2048a64707912e14ad71675fa00cc1f10af472d23df6eed43330fe643cfc45c5"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.i686-linux-musl.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "df6f3cb5de26e3781f32bafaeec2ac510e91e1d2"
os = "windows"

    [[Glib.download]]
    sha256 = "9ba7366afe33b7db919f20b2ec9f2918d6bfd72d86534fc88a9c2fb4aeb6fa64"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.i686-w64-mingw32.tar.gz"
[[Glib]]
arch = "powerpc64le"
git-tree-sha1 = "aacf99b555f3f79c51d50490070030ac797fa1eb"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "da0f923ccd69789d7377b0e375af477c7d316478b0b1d084de7953dc4b284756"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.powerpc64le-linux-gnu.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "b889219264fe47da5d9b809953b0b069f16f440c"
os = "macos"

    [[Glib.download]]
    sha256 = "d47f5a91fa0d1d13aaa2113b3b469dd12398b0845923a76f7dc240f148b7d921"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.x86_64-apple-darwin.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "654f95a1468679684421c7956e4417b4cf415a7e"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "d0b728c57aa9f057876fb7e8b832a2d2991d2ae4782448c618ad0862c4ee6757"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.x86_64-linux-gnu.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "a022754dfa2544171fb7243d675e770aaf0da362"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "4341e1d56902796b2cf423963a124d11948fb6b8b804d2fe5595958e584a92d1"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.x86_64-linux-musl.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "c2d540df3d0269bd5442aec647d10487904ae0e0"
os = "freebsd"

    [[Glib.download]]
    sha256 = "4fc6e620792806a740ab6dc5227823ea80fadf2c0e6c34cd31e383c78505d71d"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.x86_64-unknown-freebsd.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "a833cd0bfaab2c12d2b9986cd28f6fbfcddbe421"
os = "windows"

    [[Glib.download]]
    sha256 = "40325cb82d00e9c59c93ebbc489de46cc057c7387992fa0cbef74be0c5bce61c"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.78.3+0/Glib.v2.78.3.x86_64-w64-mingw32.tar.gz"
