[[Glib]]
arch = "aarch64"
git-tree-sha1 = "95f332911a8dd5ab82620ba58c217193bd0d515d"
os = "macos"

    [[Glib.download]]
    sha256 = "9634924d2ce64a372301a6ed5695bf2a38bfd928085818a7c04d2b43c810a47c"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.aarch64-apple-darwin.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "2bcfa946b47ff6cd77d7687a4b65d0236b140011"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "5d69cdb9679e6c443c7d37550d87c20152389809f96932b167200b003c204186"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.aarch64-linux-gnu.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "a679e6f641c10a88ab9d32aa7a64f2c4e0ca6953"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "de85771914d39ac484d1a9c72b142363b3e1a130e2ebf25d94beae881e1d4b2d"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.aarch64-linux-musl.tar.gz"
[[Glib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eab8ca9715bceeb0a84dda7ae64e660d2d591fcb"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "81a2e4499f83abb6b1edc7441a3438ea2dccd366acbed054d333c50a9b960149"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.armv6l-linux-gnueabihf.tar.gz"
[[Glib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e1c01324152377f8946230a8a4c4eeb2d8d348ce"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "e80898f005698099529bf5b945d63fa808f3f869f02be382f7816b8a8c990319"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.armv6l-linux-musleabihf.tar.gz"
[[Glib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1b4cd2fa89d4a75ba3684780596c38184cc175af"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "6753a75bb5010aa8c8bf934fe6b45e7710409a33ac789b0505de38de689bb7de"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.armv7l-linux-gnueabihf.tar.gz"
[[Glib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "548156819e15de7aa8d187d1fc3b291134602b6f"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "4b9fd311d09491f6c3315948c22518744327d00c7b353037490a5b3fcebc1bfd"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.armv7l-linux-musleabihf.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "d202e9abfbc530351203fc4250fc80e69a8bd072"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "cb675d2fd2241ad1a473b1507637f67cec2fc9b0dca93e53367f4c8b2fcaf47b"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.i686-linux-gnu.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "2b487afab038593f4e78bd4f03816ec81bd97d8d"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "ab21f98badde19d9cd136752f145a31eb188b97acfa2873b2113c893268215ff"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.i686-linux-musl.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "8efe712cb9fee87a880d5cbe295a0ef9b08144c6"
os = "windows"

    [[Glib.download]]
    sha256 = "f3cf8a498c30262497bc2f7f9504c65d123b336f2e12f3467322c9bc2b35b6c4"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.i686-w64-mingw32.tar.gz"
[[Glib]]
arch = "powerpc64le"
git-tree-sha1 = "4d0a8751278856146648c009eb5990196deb8e43"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "f4fabaf1b09f82bc3a71e3b21def7f06d86001b774d3239ece50ebef41187a0d"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.powerpc64le-linux-gnu.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "d2ea466e9d726fe2dc83e2179336f2098f5724a2"
os = "macos"

    [[Glib.download]]
    sha256 = "a06558dea643b204b024f2cf620311331425f7894478ee67f21a017356746a2d"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.x86_64-apple-darwin.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "b6ebc4def1211ec4043d7c055f450d59f56747cc"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "6c1bbe9138b4275e9c1854e09c310135bdef7ee6573d46c1567c5cf39bdf0b43"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.x86_64-linux-gnu.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "98592ac4772c6e622e49b87ca9ff2f5693a14e94"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "26a2ce40e36eeccb1a38e83dade4a794e64101e24e95faed5b92ca2d293589dc"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.x86_64-linux-musl.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "d1d81444118f6349c95e2e621c97292e52cca45c"
os = "freebsd"

    [[Glib.download]]
    sha256 = "de4335d35d2721b15eadddb2dc3c1f700d5a5867e7dc6f78985bf3b6f0483873"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.x86_64-unknown-freebsd.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "13606487e48c4dea9d20813adf4f03a3edea59fd"
os = "windows"

    [[Glib.download]]
    sha256 = "c1e61ab29cf82606751a2ec6a5e923399697c934ec8f01cb5e4f8bd58e182a38"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.76.5+0/Glib.v2.76.5.x86_64-w64-mingw32.tar.gz"
