[[Glib]]
arch = "aarch64"
git-tree-sha1 = "b711a7e9caf6ba516fdf5a38a3cc844bd91be9a9"
os = "macos"

    [[Glib.download]]
    sha256 = "e4fcd78dcb2fde07b79d4c5fe37d402c1dec708be448207807a427bdcfe103d0"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.aarch64-apple-darwin.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "261a7b87ae8c26d9d4b7af08341573eb8502b716"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "70ed8d936625591a2776a3ce134cfb58df1860f6e4019169a7a583cc0afdb319"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.aarch64-linux-gnu.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "e94a1bb5e019e47e1bce991f4a9064728a46c908"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "3edf5a7d5a973fe231c5682eb14fc44d7250d09c61481f303169d747c3c236b1"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.aarch64-linux-musl.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "406baea01666e61da4af71825e62ea718899afe3"
os = "freebsd"

    [[Glib.download]]
    sha256 = "fd4539ff3f57702429f6e336a1383144075b091e7857fde184ae45c75d17a018"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.aarch64-unknown-freebsd.tar.gz"
[[Glib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4464d79b6ccb2aec7e929c345e5bd87174cddd34"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "d3e992562040a9de40f9ab6f4e9d6df0f6c2e1b2a93938252d3c427d6ab40e8b"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.armv6l-linux-gnueabihf.tar.gz"
[[Glib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7b470f1208614b5c02836cc29843ef5a21b6ffc3"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "c4c6c2f01b46e1f0b06cecf4adfdad6c3cc1ef8f4b160ade990e6bb2a56dd0ec"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.armv6l-linux-musleabihf.tar.gz"
[[Glib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8db8f2a2c2f947f991a0edd44d377d88e076fb9e"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "802f82ddebb2aced31085e22ec5b5a9bed1f1317dc64f28987406dec1e73fd3f"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.armv7l-linux-gnueabihf.tar.gz"
[[Glib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c30b2ce0a2d1521bf1ae88c02cb0e27fe04c4261"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "b75daaadf25f9f12923219ca07f001b74cf911db147392ea94e0658e04c17e15"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.armv7l-linux-musleabihf.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "f856c6893feca262338078c3a5c13556484cd3ac"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "3246bff23cbfd38dbca89b85e065d276a1dc6e6ec3b4e81d5c871065bc1d5a3a"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.i686-linux-gnu.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "7631a557f74e7edee99f4cd3c2c66aa6f28e9e72"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "eba44b4ee950f252ad71222cfc5e146deef2a5ab1a9d47a938ca87a9de188451"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.i686-linux-musl.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "cb96719d73cefe05fb3908effbc395c21b3ea3d5"
os = "windows"

    [[Glib.download]]
    sha256 = "f93775c3554ab4b3737e15abfcd76597e757e7940294efc171fff7e470210302"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.i686-w64-mingw32.tar.gz"
[[Glib]]
arch = "powerpc64le"
git-tree-sha1 = "adb9ba35a2c3046da9cc74183dacb50b75ab29c2"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "f831193c1c13fae8dee24df12f999c291d98372726a0e5a68736612004ce39f1"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.powerpc64le-linux-gnu.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "46e46e08c40cebe42029bde0a5d8c2e8df2cc4d7"
os = "macos"

    [[Glib.download]]
    sha256 = "1cadb994e79dfbc8c95da387f2fddfdaa55b9bc5c89e38e09d694caf79bb13e6"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.x86_64-apple-darwin.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "b757190a3c47fcb65f573f631fdd549b98fcf2e4"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "e3ae51f90b0cbe14f74c94959390d3e71d414202fff9059b01328ddf12404977"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.x86_64-linux-gnu.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "490ca584339a254e81c42aa6971ad88cc536677a"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "45d57a797e7b4c415dbe59601540f5a884554af75d326af72c38dfb592f650ba"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.x86_64-linux-musl.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "09e92a7827754e0abf7b6aa92f54088e73352f76"
os = "freebsd"

    [[Glib.download]]
    sha256 = "567abb3640ed106a16d581873f66a0eb3d809a00f2e860a981008f27738c06d8"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.x86_64-unknown-freebsd.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "9865620c668767b40c23c527044f8f1dd03bc081"
os = "windows"

    [[Glib.download]]
    sha256 = "90f454921ac48aa0ad2fe2c5408fe2a27738efbfaf79a24dcc294593eba8925a"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.80.5+0/Glib.v2.80.5.x86_64-w64-mingw32.tar.gz"
