[[Glib]]
arch = "aarch64"
git-tree-sha1 = "8b6f6a9056d56705f0b952c245ffd68d6d9ccf49"
os = "macos"

    [[Glib.download]]
    sha256 = "d77e09a82f742d3c8b795121af66fb3be754b7f9e692341dd3259c92d0e571d3"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.aarch64-apple-darwin.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "c41499505248583f3515b94fe4d3cff1e67d96c0"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "f63548a398e837697299bda124e68aaa54832fd03964d9948dd05c3ef2bf206d"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.aarch64-linux-gnu.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "314dc402f4a5eb7c2ce50173c568cc563efd31df"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "b0c5a62ee32f396e8a8b55fa57306a8c1ea5a38ca31ebd2705bd9465e16b7e90"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.aarch64-linux-musl.tar.gz"
[[Glib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "81f12ea72072323105659a71740086bb2ffcde52"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "a422c8eee03b1cc14b478c2fbdc304bc274a1fb9535142391c8a46afd5fb42fb"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.armv6l-linux-gnueabihf.tar.gz"
[[Glib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b2df259e39db99ab47ec917d107db4362cd45c85"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "bf009f6ae3c690750a3007ed1ed3a5f8fe3a9189610c7529a46d37a1842833c8"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.armv6l-linux-musleabihf.tar.gz"
[[Glib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "34733ed6c75d63c19f4bdbd7be33abf1e0c0987c"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "91a7262723c51a9a0a129b4d07dc005b5c61d42556bb47fbcd84890e71e1dc48"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.armv7l-linux-gnueabihf.tar.gz"
[[Glib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "751ed176ce5ca909e59fe0783e344bfe45246db6"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "47aa56dfb8eb1b7246075aab96049641365fcbf24288bfe46a7b59ec32fc4510"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.armv7l-linux-musleabihf.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "145916bdbf3558bf3c87e20ba6ee96007142c1cc"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "20ac6df5738c0655bda7652d07ca52d6b1fc95631e88c45c0f67660ea4ed1056"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.i686-linux-gnu.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "02bbf69f99bf1a017b7b3e9cb243c8542d2b3e92"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "fb0d41921e2a2f9ffd1d6bafb524e6504610a4c4f925f8f3f5ec0ac2f8be4565"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.i686-linux-musl.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "c03c9c3a0471d65532bfcb5ac2004bd13c09168c"
os = "windows"

    [[Glib.download]]
    sha256 = "b32c582544fd440946426217aa4726db1b22a340eb3b1a4ad2214d151b875f8a"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.i686-w64-mingw32.tar.gz"
[[Glib]]
arch = "powerpc64le"
git-tree-sha1 = "ab20d7a8602301f6a22ea2774993dc7c96cb4721"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "9cc08a41fb8c14791498aac30f9dbd31cd4aa24aea2e0c6e9c2992fcae238030"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.powerpc64le-linux-gnu.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "e061d5e73ef4be8e21e1e9ce117be0168835c4ef"
os = "macos"

    [[Glib.download]]
    sha256 = "0e7eeccc70e383a618c781469445d3d4e78eb0436e7e669b7b609292b789c796"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.x86_64-apple-darwin.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "8cc532f6a1ace8d1b756fc413f4ab340195ec3c3"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "43815936067ffecd1eb13814f9d0486353deca18c547ec58b26235ed0bf3918e"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.x86_64-linux-gnu.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "3a42deac41741494dbc86edbacc2516e692f946c"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "bd8ac60fcf15877b82cfbb0b132fd5593c1f29e89252da60f1efb07631e5fc2f"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.x86_64-linux-musl.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "60fdd4939440617aa428ffed49e1e6441a99e271"
os = "freebsd"

    [[Glib.download]]
    sha256 = "fd4d89fad2fa6f3b8579ca35f28f47932f0ade5875be18e1d365833b3d2b21a8"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.x86_64-unknown-freebsd.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "f62699263c6869e302e2212a594e80392d899fcd"
os = "windows"

    [[Glib.download]]
    sha256 = "689964ec616be612a87abce79abc6182a66c87bced9799834ab4f793f1f6360b"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.68.1+0/Glib.v2.68.1.x86_64-w64-mingw32.tar.gz"
